### ISSUE TITLE
crash witch join

### ISSUE THREAD

**Issue by majovec** [DarkYusuf13/DarkSystem#14]
<18:20:16> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:16> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:16> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:16> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:16> DarkSystem 》 DEBUG: #3 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:16> DarkSystem 》 DEBUG: #4 (): raklib\server\RakLibServer->run()
<18:20:17> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:17> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:17> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:17> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:17> DarkSystem 》 DEBUG: #3 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:17> DarkSystem 》 DEBUG: #4 (): raklib\server\RakLibServer->run()
<18:20:17> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:17> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:17> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:17> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:17> DarkSystem 》 DEBUG: #3 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:17> DarkSystem 》 DEBUG: #4 (): raklib\server\RakLibServer->run()
<18:20:22> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:22> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:22> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:22> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:22> DarkSystem 》 DEBUG: #3 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:22> DarkSystem 》 DEBUG: #4 (): raklib\server\RakLibServer->run()
<18:20:23> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:23> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(178): raklib\server\Session->handlePacket(raklib\protocol\OPEN_CONNECTION_REQUEST_1 object)
<18:20:23> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:23> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:23> DarkSystem 》 DEBUG: #3 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:23> DarkSystem 》 DEBUG: #4 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:23> DarkSystem 》 DEBUG: #5 (): raklib\server\RakLibServer->run()
<18:20:23> DarkSystem 》 DEBUG: An E_NOTICE error happened: "Undefined property: raklib\server\SessionManager::$serverId" in "/src/raklib/server/SessionManager" at line 391
<18:20:23> DarkSystem 》 DEBUG: #0 /src/raklib/server/SessionManager(178): raklib\server\Session->handlePacket(raklib\protocol\OPEN_CONNECTION_REQUEST_2 object)
<18:20:23> DarkSystem 》 DEBUG: #1 /src/raklib/server/SessionManager(102): raklib\server\SessionManager->receivePacket()
<18:20:23> DarkSystem 》 DEBUG: #2 /src/raklib/server/SessionManager(94): raklib\server\SessionManager->tickProcessor()
<18:20:23> DarkSystem 》 DEBUG: #3 /src/raklib/server/SessionManager(82): raklib\server\SessionManager->run()
<18:20:23> DarkSystem 》 DEBUG: #4 /src/raklib/server/RakLibServer(233): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
<18:20:23> DarkSystem 》 DEBUG: #5 (): raklib\server\RakLibServer->run()

**Comment by DarkYusuf13** [comment]
Thanks for issue will be fixed
