### ISSUE TITLE
Eror When Join

### ISSUE THREAD

**Issue by Amirgta1** [DarkYusuf13/DarkSystem#16]
Notice: Undefined variable: ip in C:\Users\AM-HA\Desktop\PocketMine-MP\src\pocketmine\Player.php on line 2126

Warning: Creating default object from empty value in C:\Users\AM-HA\Desktop\PocketMine-MP\src\pocketmine\entity\Living.php on line 45
<18:27:50> DarkSystem 》 CRITICAL: Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/src/pocketmine/entity/Living" at line 48
<18:27:50> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
<18:27:50> DarkSystem 》 EMERGENCY: Please upload the "C:\Users\AM-HA\Desktop\PocketMine-MP\crashdumps/CrashDump_Fri_Oct_20-18.27.50-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Amirgta1** [comment]
DarkSystem Crash Report Fri Oct 20 18:27:50 UTC 2017

Error: Cannot use object of type stdClass as array
File: /src/pocketmine/entity/Living
Line: 48
Type: notice

Code:
[39] 		if(isset($this->namedtag->HealF)){
[40] 			$this->namedtag->Health = new ShortTag("Health", (int) $this->namedtag["HealF"]);
[41] 			unset($this->namedtag->HealF);
[42] 		}
[43] 
[44] 		if(!isset($this->namedtag->Health) or !($this->namedtag->Health instanceof Short)){
[45] 			$this->namedtag->Health = new ShortTag("Health", $this->getMaxHealth());
[46] 		}
[47] 
[48] 		$this->setHealth($this->namedtag["Health"]);
[49] 	}
[50] 
[51] 	public function setHealth($amount){
[52] 		$wasAlive = !$this->dead;
[53] 		parent::setHealth($amount);
[54] 		if(!$this->dead and !$wasAlive){
[55] 			$pk = new EntityEventPacket();
[56] 			$pk->eid = $this->getId();
[57] 			$pk->event = EntityEventPacket::RESPAWN;
[58] 			Server::broadcastPacket($this->hasSpawned, $pk);

Backtrace:
#0 /src/pocketmine/entity/Entity(499): pocketmine\entity\Human->initEntity(boolean)
#1 /src/pocketmine/Player(3836): pocketmine\entity\Entity->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\LongTag:1508412523325.pocketmine\nbt\tag\LongTag:1508524070131.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:8.5799998092651.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\StringTag:world.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:2.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:3.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:4.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:5.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:6.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:7.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:8.pocketmine\nbt\tag\ByteTag:255.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:9.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:10.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:11.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:12.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:13.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:14.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:15.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:16.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:17.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:18.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:19.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:20.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:21.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:22.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:23.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:24.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:25.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:26.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:27.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:28.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:29.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:30.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:31.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:32.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:33.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:34.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:35.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:36.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:37.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:38.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:39.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:40.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:41.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:42.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:43.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:44.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:45.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:46.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:47.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:48.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:49.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:50.}.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.}.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.}.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:1.5200002193451.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\StringTag:EachKestrel953.pocketmine\nbt\tag\ShortTag:20.})
#2 /src/pocketmine/Player(2915): pocketmine\Player->completeLogin(boolean)
#3 /src/pocketmine/network/RakLibInterface(172): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\ResourcePackClientResponsePacket object)
#4 /src/raklib/server/ServerHandler(94): pocketmine\network\RakLibInterface->handleEncapsulated(string 192.168.1.50:34971, string ......)
#5 /src/pocketmine/network/RakLibInterface(106): raklib\server\ServerHandler->handlePacket(boolean)
#6 /src/pocketmine/network/Network(162): pocketmine\network\RakLibInterface->process(boolean)
#7 /src/pocketmine/Server(2539): pocketmine\network\Network->processInterfaces(boolean)
#8 /src/pocketmine/Server(2334): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(1885): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1804): pocketmine\Server->run(boolean)
#11 /src/pocketmine/PocketMine(336): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\AM-HA\Desktop\PocketMine-MP\, string C:\Users\AM-HA\Desktop\PocketMine-MP\, string C:\Users\AM-HA\Desktop\PocketMine-MP\plugins\, string Bilinmeyen)

DarkSystem Version: 2.2.1 #0 [Protocol 138; API 3.0.1]
PHP Version: 7.0.17
Zend Version: 3.0.0
Operating System: WINNT, win

Number of Loaded Worlds: 1
Players Online: 0/100

Loaded Plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH REPORT===
eNrtHYty2zbyV1AlM7VvRIkPPXnnzLiJ02Sahy92pjdXdlSIhCTUFMgSoBXl8e+3C0ASZVtJ2vQ6
U4aSUwmLfWOxC7Jc+11L8SVrhV7fHfX9njt0262USnVWFFnRCt+11DqH6ZbIFI9Zq91aMinpHEEP
qQAoKSUj2fRXFiuSzQiiE6mSh8BEEgo/RUHXQDcr0/QxTzVhGEWvJStkFJ0+d56cRtEjJq9UlkfR
eRZfMfWcC+Y8P48iWcRRlGvYEmBRxITiah1Fz/g1F/NOvsiRtWHbBezuDrlrcLsGFdBSALbC3qjd
UgUFW8KfWvdccoDqTH8c9cbj45DcpcGTckmF84ALrizuNMtSRsUxiLrn3eJ7ntI1K46CUTA4wNGw
cR5MJnEmpCrKWB1V8VJ2zVIwHT+sx9t7jMRURZGi8yh6mC3zrBTJJ6bfde6ef5aJ+SWd66DoeX7f
DwK//xm4JoC8wDuAeybKZXh46pA6j7JymjIU4n4SY9TpD8fwGrljf9D3PoPjhwM4F6rgxrRVVqTJ
n2vSZgXCP7ZAF4usUB9zyHdrpc3zvpTBp+b9fv+gB/82Rnpfg5H+12Bk8DUY2fsajOx/DUYOvgYj
h1+DkaO/gZHulzIY//1N8Nwa2ODVwAa/BjYENbChVwMbapBavUENbBjWwIZRDWyoQZ32a1Cn/RrU
ab8GddqvQZ32a1Cn/RrUab8GddqvQZ32a1Cn/RrU6aAGdTqoQZ0OalCngxrU6aAGdTqoQZ0OalCn
gxrU6aAGdTqoQZ3u1aBO92pQp3s1qNO9GtTpXg3qdK8GdbpXgzrdq0Gd7tWgTvdqUKf7WKc//NGH
Df90ws/22/+NwVPxUb992fRf8ECq+wWPoP5B9R6nGf2o2RWED59C8Tp934WX742DXv8PPyezRQjc
L33k1P3kA7tnNF78wKQqWDruB5/SCP9Xk35o2z/00LY/9vo3Hto2M86DGAI4ZYo9y+Zc7D0CHtzi
JphaZcVV9xW9esanEJqsmNGYHXlD/wD3BRVJyh5RRc8pzu49D27ZRVFeZCqLszSKXjGZlUXMEPth
yplQAMkzIZmht4+Na/16Rr+CXqV82pWsuGZF90J/PNFii6Nx74ZeW5E3TNhoeiZimssypYolR1Kv
B/HGfscbjDoQSG4Y9MZDr03sVEe/tDb9z/eWiw/QG7WjyOgNq1lVfKOOdVp1VQYH5bwwn0fewP9s
q8HzMZNyT8LwlgSj25HfD8aHOFvhW45bGfu8Rwd5B8HNtTIzzgPF46s9JuNDTLzRqP8RJudGtazY
73RwD7NzD+lUlPt7xbujX2LbCXIU3GqZ2PCptkp8RyXTXSfPMpqw4s4OiVLxVEbRc8oFbNh5BctG
5Oe3pvw1JHlaQl6RFdrveMrFkq0ZeO7nD+0W+9MbdX5fNw2oYJRshTOaStZuxVnCUKFgDGwiFSk+
O+JSwka8rxZcOg8EXbIEcrDz4Amj6ePj43fAr+da7EjdiaYW5IQItiKbvH0UtQw8arXJERfqmNwg
/MlgPI5aPx//E0V4WxGl+Ig+Gte3uB9wEMAAP3s7i775iElqcUyygnxzaJbAkioqYgbroM2xLuh/
iQssyRyih74x4KNjY8ugasvQ2jKyQEsHxliiu72IQqwbzbois75rmPWNZ3M40vCYzEoRK54JUuFJ
l3DMU9rM/sa191dUnqb8moFZ31ipCaMJCukHFimnBYReGN7mpdGqK1JhQSD/A8+NACO34t78yrrS
NF2dXYMMWy0M30EV13nAeAIEOxc/TSze8AYeMgLMW2zD8NXZxfnpjy801WhLZTJZGE4LyFoxlRst
rKgFlRc5XQmWwALnVyDzQ9O+1rSvNe1rTfta077WtK817WtN+1rTvta0rzXta037WtO+1rSvNe1r
Tfta077WtK817WtN+1rTvta0rzXta037WtO+1rSvNe1rTfta077WtK817WtN+1rTvta0rzXta037
WtO+1rSvNe1rTfta077WtK817WtN+1rTvta0rzXta037WtO+1rSv/UXta+3WnAlW0BTbxbDfqBW2
HtHi6mItFVuCZ8FLkmcCwH4HtiFApiVPk1botlubtNEKvWDUbtGcA1rQcTWa2V8AcDujjguA0rL/
kYskW0ny4pI8Orv44fLluRMMf/DHj18Tz+24RPMnXi8YB+Rog+y5x+T0+aNBDxjhn5wKW0OUM4Th
WyYSK9c1s5NMopynL15cAkAPVly0tn1yAPgJLM9pARrBNrFjkwk6YFXOCsUZ0t3bOYOcbycI/hmt
qIjEvccFJy9jRXyXeCMoBKE/JK8vH8LYGyKC4emg6ScSActMJeabncqhiJx4Yy/wEZgJ7OpzllnC
TjKBEN20YxjoNpIdDPsHTx6dPT59/ewSoXPA0YSuFkTfOLmuAvLEczVIYh+Tg6vGdHfYieMhGHsT
SwHZyKA7UPs4CFhC8pcn2WyGOKsFV8xJuVQbCBMUjh/ObyUr1lZVCypgS22wrJE8P3E7+q1VAzWL
NXBbcnXi9wfPtRZpmq2cWcrni60MozAVfElTaYXYkaWu2LXMphsc/FpFmGVQ0pytfwzSghZJnBVs
Iyy/zu1MwmczHpepWp94FbugUi+hKjjTFLaYRTW7R2WFI5lSsL3kyW6BJGOJHqJHOjlkFljB5OQf
+gWWlCpzJL3eKKTHluEGhtObdUmgilsw/sU4p8yTHWIpmcNEXKzzrfdwM2xTV2e9TDGeJ/pFdi/9
/U7g/guC/b2eiKIt7D28SVeTv98H3kWs3yBGvyc4mgCvXxyno+VNDJv3+lOPiFFqS9wlk1/g41uN
1iVdTQos7BxAJxP4RNC3E/KL+WbJAZ0cTQwfreC/ulGE6F2Q+J7gd80KbQTo++0byScIQpT2BJGR
AkYI2E4QjYRfNfi9tsT8Aw7kYy8j7+7XJ2iNUIH7zERfGAly73JRMNisAIL6lFIxL+mcEWwKJrAT
iN2TksMYQpmm/C3FdICkDxcsviJrOAPeIMwEWSiVy7DbZaKz4lc8ZwmnnayYd3HUfQa5YZLNJk8v
Xk4GwdjxJ0gngemGUUiiFhPzqIWCflwwtQD1VAb6iITA9rcFShJVUCH1EdBMo7pGU4ZNvWAYAVqS
sGseM2JOaghZAmOz1XciobQzK09sWMlFqQiUFdHWfGyWJCsOOsyB+RWcVZhpYMUeUAI/qwVVBkEu
shV6A7VnRMbgatEBCcgUeTq26xutNacMMqVQP5AwMbafYqojmEyxHtuaRK45Jf/GbAooOqs6dmZn
xAXKpgSPLHD0IVYSKAe2UcsIm8wl+CYvWKxdeHr+FDAVSMfF2E04oNo0kxUfnek8t+GD5mN+JFAw
ZnhmmJPpGuhnFDIjoNusuJ2tqAk+5Ao72i2EJtfYa504MdSWncAyF7kDC7aCTKwZ6PZ1w0EkEjTI
xHqZlRIiAyIU3BVLjAjwORgAhqLxBcMKiqZhHDml3Fv2F+Vyioe0GTmVaxFfUnlF8JyMRyeMitNX
L56++D4kl7jOen25QPaSkXmaTWlKTLEywtpwONGmrTLxrSJTphcRfMx1PIBuiqYYDBSFOVZQSDzc
ogmblnO9P5/OyAMCFzG8GlJ6erOkcsPRLjXuIiwpmtVmoSQcecEvJVpia9M2VnYlaC8vsM364T5Z
UtxH8B+Nas3HX1Gg48k4OdEho0kcQxLCslzz1NqB0tqoJQSTkmRWZEuIxCpz8Cv+6gNVkQ1LqG6r
AnsqhYO3XrWXl2d2TeAnLgtsQE/XmhHHy2U8m2jdrOStbtsIOoViChAOSQMIY0gSECvWULwWIVhk
UZMlHOUV/MMjHE5IkmOKYMAZBeiijHAHCXYC9uHmsBECDxv/Uls4xTjaSTvyyMldYtrEhwnvrgmm
4s4x8EROVTV0GFwiZ0ycmwzGYHsZedgFb9Yx02l2Ewck4VKftHRm06GaruhaGt6Wz9bKSMSLUlw5
uLNwg2rH6tZ/3FF6TuK200u6UQLVR26ADF81Y6sv3qsrIMDxFxPopcBoS4yaVoRl2iFP4BwIjE7I
ElPQw/PXbSCREhwhkhVP1MLsSBP6G66O3SSDw4rSQre1a08ZjQEXz8oGCZawP9gZjspvDH9O3xB6
k6e92mbJzvd7dut4eEUTDklsR2WVoFYDvSEMpV1ixA9J7/ftBX10tqfC3RqSGC6SjTr6/H5rce2J
E9wX3ijMcJGtw3iHgZuUEjwfs0IvO5w0aIJF2VREvZssFJl9v6PU2QUzJq7iPOUqXqzvoDIpViOn
dK5XHxm9lhgcymRpWPwZlFSyPXxr10BZgyQIYaSdgcnJVKikbbNNwk1BrJhj9V/SNehFr2yyj3QR
dXQSr6QUCIDO7QgAP23O7NvQb4NhsER42LqD0d6u2K5CHJopniUOFxoBFnEAV24Cz/swcmAWkcwV
kKOvejBKEAUcJaASFVuoZ3MUXkBoNoiky6+DASHKPCRjw9xcPukMpuvEhhdwGSKVFYhM+zhcURS0
BWoYXU7xZqFBsZcypjKHm3oOFYXKxaZea+fY3QNLuz1PJDs/6XqOh8htOdeQbUnbg8JlP4frvB31
IsNY1zIr9287gimtYMoho5qyePaG4j4yA6zFEC72tkdI7Bc9Ba6UKgPH/aQvyyCP4k2VLP8ZOeqL
c+QBl13sjWICySTeVnkIMVy9YTGNoTAtqhA82YqEFnsw+9uEtgDc1tUxnLpgHaqQBdgKY0/fB+FY
Gquzv0p9G8fr9PT8Ul8rVhEuzp9Vh3m8r/YrNkvNfYMqVJrMuwdSFI1JqrDlWv6W6vs09hvp45Tv
wCGeOHi7pO/23CF8vf8UQmDaj/tjd5D0+j7Db8PAp+Ng6va9WTDyh8z1h73xdBSQ+8BbZVdM8Lf7
vnjLc22sF3T6ODT3orbTMHyjL4h37s2WeJPLdQPP88cAOH/0sjqf5bCkco/kQuff/zzfc9sNtqsk
eXNjGlPOvrIAXBX8xmr+CAmpYDN9By3oBBgSZZHecirfcz2MFQs0zRB9izAd/HKPcGoutaqwNdWK
+/Y22ny5d5MtN5lS6httXmeA/lnogEUCH5XLlpMkU7C/qnT/xY3/8lwnnh38w4f/AbROEd0=
===END CRASH REPORT===

**Comment by DarkYusuf13** [comment]
Look at latest commit fixed :)
