### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Amirgta1** [DarkYusuf13/DarkSystem#20]
Why does not the steadfast bug break?

**Comment by Amirgta1** [comment]
I think it's better to start from the beginning and use the steadfast source and add functionality.

If you can add Api 3.0.1 to it and add resource packs and behaviorpacks and solve the command.json problem and then add some capabilities to it.

**Comment by DarkYusuf13** [comment]
Already them added and new api will be added in 3.0 update, follow we. Resource and behavior added but dont work

**Comment by Amirgta1** [comment]
Why do not you get help from Turanic? They solved a lot of problems

**Comment by Amirgta1** [comment]
In my opinion, the main problem with Darkstar is the problem now

**Comment by DarkYusuf13** [comment]
I will fix on 3.0, thanks
