### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by flayzer** [DarkYusuf13/DarkSystem#21]
<12:54:00> DarkSystem 》 INFO: [SUNUCU: qherreid добавлен в вайтлист]
<12:54:11> DarkSystem 》 CRITICAL: Error: "Call to a member function addEntity() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 492
<12:54:11> DarkSystem 》 EMERGENCY: Произошла фатальная ошибка и сервер вышел из строя. Создание аварийного дампа
<12:54:11> DarkSystem 》 EMERGENCY: Пожалуйста, загрузите файл"/home/server/crashdumps/CrashDump_Mon_Oct_30-12.54.11-UTC_2017.log" в краш-архив и отправьте ссылку на страницу исправления ошибок. Дайте как можно больше информации.

**Comment by DarkYusuf13** [comment]
Please try to change current world.

**Comment by flayzer** [comment]
@DarkYusuf13 You can fix the problem that on version 1.2 you are attracted to the ground?
