### ISSUE TITLE
1.2.0 join error

### ISSUE THREAD

**Issue by andris155** [DarkYusuf13/DarkSystem#3]
![kepkivagas](https://user-images.githubusercontent.com/8324198/30783517-62a8da3c-a144-11e7-86fb-b003a60967db.PNG)

**Comment by DarkYusuf13** [comment]
DarkSystem support 1.2 (packets etc.) but joining haven't initialized yet. Wait, It will come.

**Comment by DarkYusuf13** [comment]
Solved
