### ISSUE TITLE
server crashes when player joins. 

### ISSUE THREAD

**Issue by Yexeed** [DarkYusuf13/DarkSystem#5]
![image](https://user-images.githubusercontent.com/32373441/31319159-026406fa-ac67-11e7-89eb-14d669b63dfe.png)
mc version: 1.1.x

**Comment by DarkYusuf13** [comment]
1.2 indev, 1.1 is damaged while developing 1.2. Wait next updates for fix.

**Comment by DarkYusuf13** [comment]
Fixed, but maybe still buggy, If crashes reopen issue.

Closed
