### ISSUE TITLE
Notice: Undefined variable: downBlock in /home/darksystem/src/pocketmine/Player.php on line 1552 <11:23:09> DarkSystem 》 CRITICAL: Error: "Call to a member function isTransparent() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 1552

### ISSUE THREAD

**Issue by erkam2002** [DarkYusuf13/DarkSystem#7]
/gamemode 3 causes this crash

**Comment by DarkYusuf13** [comment]
Movement is buggy on 1.2 on so much server engines, we rewrote movement for gamemode 0 and 2. Creative and spectator not implemented yet. We work everyday for moving.

**Comment by DarkYusuf13** [comment]
Tested again, didnt crash. Solved
