### ISSUE TITLE
Crash on AddUi write /addui noob

### ISSUE THREAD

**Issue by erkam2002** [DarkYusuf13/DarkSystem#8]
Notice: Undefined offset: 0 in /home/darksystem/src/pocketmine/command/defaults/AddUICommand.php on line 42

Warning: strpos(): Empty needle in /home/darksystem/src/pocketmine/Server.php on line 866

Fatal error: Class pocketmine\inventory\customUI\windows\SimpleForm contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (pocketmine\inventory\customUI\CustomUI::close, JsonSerializable::jsonSerialize) in /home/darksystem/src/pocketmine/inventory/customUI/windows/SimpleForm.php on line 8

**Comment by DarkYusuf13** [comment]
Will be fixed on darksystem 2.2. Check out when out

**Comment by DarkYusuf13** [comment]
Fixed
